#![allow(dead_code, clippy::upper_case_acronyms)]
// ============================================================================
// Typeway Spike: Type-Level Web Framework Proof of Concept
// ============================================================================
//
// This spike proves three core concepts on stable Rust:
//   1. URL path segments encoded as type-level heterogeneous lists (HList)
//   2. HTTP method encoding as zero-sized types
//   3. Compile-time handler type matching against route specifications
//
// This is throwaway PoC code — not a polished library.

use std::marker::PhantomData;

// ============================================================================
// Step 0.2: Type-Level Path Segment Lists
// ============================================================================

/// Heterogeneous list terminator.
struct HNil;

/// Heterogeneous list cons cell. `H` is the head element, `T` is the tail.
struct HCons<H, T> {
    _marker: PhantomData<(H, T)>,
}

/// A literal path segment. Each literal is its own zero-sized type that
/// implements `LitSegment` to provide the string at runtime.
///
/// On stable Rust, const generic `&'static str` is not yet supported,
/// so we use marker types + a trait instead of `Lit<"users">`.
///
/// The proc-macro layer (Phase 3) will generate these marker types from
/// string literals, so users never write them by hand.
trait LitSegment {
    const VALUE: &'static str;
}

// Example literal segment types (in the real library, generated by macro):
struct Users;
impl LitSegment for Users {
    const VALUE: &'static str = "users";
}

struct Posts;
impl LitSegment for Posts {
    const VALUE: &'static str = "posts";
}

struct Name;
impl LitSegment for Name {
    const VALUE: &'static str = "name";
}

/// Wrapper to mark a type as a literal segment in the HList.
struct Lit<S: LitSegment> {
    _marker: PhantomData<S>,
}

/// A captured path segment of type `T`. Parsed from the URL at runtime
/// using `T: FromStr`.
struct Segment<T> {
    _marker: PhantomData<T>,
}

// Demonstrate that distinct path types are distinct Rust types:
type Path1 = HCons<Lit<Users>, HNil>;
type Path2 = HCons<Lit<Users>, HCons<Segment<u32>, HNil>>;
type Path3 = HCons<Lit<Users>, HCons<Segment<u32>, HCons<Lit<Posts>, HNil>>>;

// --- Tuple prepend helper ---

/// Helper trait to prepend a value to a tuple.
trait Prepend<T> {
    type Output;
}

macro_rules! impl_prepend {
    // Base: prepend T to ()
    () => {
        impl<T> Prepend<T> for () {
            type Output = (T,);
        }
    };
    // Recursive: prepend T to (A, B, ...)
    ($first:ident $(, $rest:ident)*) => {
        impl<T, $first $(, $rest)*> Prepend<T> for ($first, $($rest,)*) {
            type Output = (T, $first, $($rest,)*);
        }
    };
}

impl_prepend!();
impl_prepend!(A);
impl_prepend!(A, B);
impl_prepend!(A, B, C);
impl_prepend!(A, B, C, D);
impl_prepend!(A, B, C, D, E);
impl_prepend!(A, B, C, D, E, F);
impl_prepend!(A, B, C, D, E, F, G);

// --- ExtractSegments: maps a path type to a tuple of captured types ---

/// Given a path type (an HList of Lit and Segment nodes), produce the
/// tuple of captured segment types.
trait ExtractSegments {
    type Captures;
}

impl ExtractSegments for HNil {
    type Captures = ();
}

impl<S: LitSegment, T: ExtractSegments> ExtractSegments for HCons<Lit<S>, T> {
    type Captures = T::Captures;
}

impl<U, T: ExtractSegments> ExtractSegments for HCons<Segment<U>, T>
where
    T::Captures: Prepend<U>,
{
    type Captures = <T::Captures as Prepend<U>>::Output;
}

// Compile-time assertions that Captures types are correct:
fn _assert_captures() {
    fn check<P: ExtractSegments<Captures = C>, C>() {}

    // Path1 = /users → no captures
    check::<Path1, ()>();

    // Path2 = /users/:u32 → (u32,)
    check::<Path2, (u32,)>();

    // Path3 = /users/:u32/posts → (u32,)
    check::<Path3, (u32,)>();

    // Two captures: /:u32/posts/:u32
    type TwoCaptures = HCons<Segment<u32>, HCons<Lit<Posts>, HCons<Segment<u32>, HNil>>>;
    check::<TwoCaptures, (u32, u32)>();

    // Mixed capture types: /users/:u32/name/:String
    type MixedCaptures =
        HCons<Lit<Users>, HCons<Segment<u32>, HCons<Lit<Name>, HCons<Segment<String>, HNil>>>>;
    check::<MixedCaptures, (u32, String)>();
}

// ============================================================================
// Step 0.3: HTTP Method Encoding
// ============================================================================

struct GET;
struct POST;
struct PUT;
struct DELETE;
struct PATCH;

trait IsMethod {
    const METHOD: &'static str;
}

impl IsMethod for GET {
    const METHOD: &'static str = "GET";
}
impl IsMethod for POST {
    const METHOD: &'static str = "POST";
}
impl IsMethod for PUT {
    const METHOD: &'static str = "PUT";
}
impl IsMethod for DELETE {
    const METHOD: &'static str = "DELETE";
}
impl IsMethod for PATCH {
    const METHOD: &'static str = "PATCH";
}

/// A route descriptor: method `M`, path `P`, request body `Req`, response `Res`.
/// Purely a type-level description — no runtime values.
struct Route<M, P, Req, Res> {
    _marker: PhantomData<(M, P, Req, Res)>,
}

// Demonstrate distinct route types:
type GetUsers = Route<GET, Path1, (), Vec<User>>;
type PostUsers = Route<POST, Path1, CreateUser, User>;

fn _assert_routes_distinct() {
    fn check<A, B>() {}
    check::<GetUsers, PostUsers>();
}

// ============================================================================
// Step 0.4: Handler Type Matching
// ============================================================================

#[derive(Debug)]
struct User {
    id: u32,
    name: String,
}

struct CreateUser {
    name: String,
}

trait IntoResp {
    fn into_response(self) -> String;
}

impl IntoResp for User {
    fn into_response(self) -> String {
        format!("User({}, {})", self.id, self.name)
    }
}

impl IntoResp for Vec<User> {
    fn into_response(self) -> String {
        format!("{} users", self.len())
    }
}

/// The handler trait, parameterized by a Route type.
trait Handler<R> {
    type Captures;
    type Res;
    fn call(&self, captures: Self::Captures) -> Self::Res;
}

// Arity 0: fn() -> Res, for routes with no captures.
impl<F, M, P, Req, Res> Handler<Route<M, P, Req, Res>> for F
where
    M: IsMethod,
    P: ExtractSegments<Captures = ()>,
    F: Fn() -> Res,
    Res: IntoResp,
{
    type Captures = ();
    type Res = Res;
    fn call(&self, _captures: ()) -> Res {
        (self)()
    }
}

// For arities > 0, newtype wrappers disambiguate (no overlapping impls on stable).
// The #[handler] proc-macro will hide these from users.

struct H1<F>(F);

impl<F, M, P, Req, Res, A> Handler<Route<M, P, Req, Res>> for H1<F>
where
    M: IsMethod,
    P: ExtractSegments<Captures = (A,)>,
    F: Fn(A) -> Res,
    Res: IntoResp,
{
    type Captures = (A,);
    type Res = Res;
    fn call(&self, captures: (A,)) -> Res {
        (self.0)(captures.0)
    }
}

struct H2<F>(F);

impl<F, M, P, Req, Res, A, B> Handler<Route<M, P, Req, Res>> for H2<F>
where
    M: IsMethod,
    P: ExtractSegments<Captures = (A, B)>,
    F: Fn(A, B) -> Res,
    Res: IntoResp,
{
    type Captures = (A, B);
    type Res = Res;
    fn call(&self, captures: (A, B)) -> Res {
        (self.0)(captures.0, captures.1)
    }
}

// --- Demonstrate compile-time handler matching ---

type GetUser = Route<GET, HCons<Lit<Users>, HCons<Segment<u32>, HNil>>, (), User>;

fn get_user(id: u32) -> User {
    User {
        id,
        name: "Alice".to_string(),
    }
}

fn _assert_handler_matching() {
    fn check<R, H: Handler<R>>() {}

    // Correct: fn(u32) -> User for GET /users/:u32 → User
    check::<GetUser, H1<fn(u32) -> User>>();

    // WRONG — uncommenting any of these causes a compile error:
    //
    // Wrong argument type:
    //   check::<GetUser, H1<fn(String) -> User>>();
    //
    // Wrong return type (String doesn't impl IntoResp):
    //   check::<GetUser, H1<fn(u32) -> String>>();
    //
    // Arity mismatch (route has one capture, handler takes zero):
    //   check::<GetUser, fn() -> User>();
}

// --- Runtime verification ---

fn main() {
    println!("=== Typeway Spike ===\n");

    println!("Step 0.2: Type-level path segments");
    println!("  Path1 = /users         → Captures = ()");
    println!("  Path2 = /users/:u32    → Captures = (u32,)");
    println!("  Path3 = /users/:u32/posts → Captures = (u32,)");
    println!("  (All compile-time assertions passed)\n");

    println!("Step 0.3: HTTP method encoding");
    println!("  GET::METHOD    = {}", GET::METHOD);
    println!("  POST::METHOD   = {}", POST::METHOD);
    println!("  PUT::METHOD    = {}", PUT::METHOD);
    println!("  DELETE::METHOD = {}", DELETE::METHOD);
    println!("  PATCH::METHOD  = {}", PATCH::METHOD);
    println!();

    println!("Step 0.4: Handler type matching");
    let handler = H1(get_user);
    let result: User = Handler::<GetUser>::call(&handler, (42,));
    println!("  H1(get_user).call((42,)) = {:?}", result);

    let list_handler = || -> Vec<User> { vec![] };
    type ListUsers = Route<GET, Path1, (), Vec<User>>;
    let result: Vec<User> = Handler::<ListUsers>::call(&list_handler, ());
    println!("  list_users().call(()) = {:?}", result);

    println!("\n=== All spike checks passed ===");

    // ========================================================================
    // Design Notes & Findings
    // ========================================================================
    //
    // WHAT WORKS on stable Rust (edition 2021):
    // ------------------------------------------
    // 1. HList (HCons/HNil) cleanly encodes path segments as types.
    //    The ExtractSegments trait correctly computes capture tuples.
    //
    // 2. The Prepend<T> helper trait enables building capture tuples
    //    incrementally. macro_rules! generates impls for arities 0–8.
    //
    // 3. Route<M, P, Req, Res> as a phantom type works perfectly.
    //    Zero runtime cost, full type distinction.
    //
    // 4. Handler trait impls match function signatures against routes
    //    at compile time. Wrong types, wrong arities, and missing trait
    //    impls are all caught by the compiler.
    //
    // LIMITATION: const generic &'static str
    // ------------------------------------------
    // Const generic `&'static str` is NOT stable. We cannot write
    // `Lit<"users">` directly. Two alternatives:
    //
    //   (a) Marker types + LitSegment trait: each literal is a ZST that
    //       impls `LitSegment { const VALUE: &'static str }`. This is
    //       what the spike uses. The proc-macro layer generates these.
    //
    //   (b) Nightly feature `adt_const_params`: enables Lit<"users">
    //       directly, but requires nightly Rust. NOT acceptable per
    //       project constraints.
    //
    //   (c) Const generic [u8; N] encoding: encode the string as bytes
    //       using const generics on arrays. Complex but possible on stable.
    //
    // RECOMMENDATION: Use approach (a) for now. The proc-macro in Phase 3
    // will generate `struct users_lit; impl LitSegment for users_lit { ... }`
    // from the string "users" in `path!("users" / u32)`. Users never see
    // the marker types.
    //
    // OTHER LIMITATIONS:
    // ------------------------------------------
    // 1. OVERLAPPING IMPLS: Cannot have a single blanket Handler impl for
    //    all Fn arities on stable. The H1/H2 newtypes disambiguate.
    //    Solution: #[handler] proc-macro wraps user functions automatically.
    //
    // 2. ASYNC: Spike uses sync fns. Real library uses async — adds a
    //    Future associated type but doesn't change the fundamental approach.
    //
    // 3. TUPLE ARITY CAP: Prepend<T> up to arity 8. Fine — 8 captures
    //    per route is more than enough.
    //
    // 4. REQUEST BODY: Req type param unused in handler matching here.
    //    POST/PUT handlers will get an extra FromRequest argument.
    //
    // 5. STABLE RUST: Everything compiles on stable Rust 2021 edition.
}
