//! Proto-to-typeway code generation.
//!
//! Given a [`ProtoFile`](crate::proto_parse::ProtoFile), generate Rust source
//! code with typeway API types, structs, and path declarations.

use crate::proto_parse::{ParsedMessage, ProtoFile};

/// Generate typeway Rust source code from a parsed `.proto` file.
///
/// The output contains:
/// - `use` statements for typeway and serde
/// - Rust structs for each proto message (with `Serialize`/`Deserialize` derives)
/// - `typeway_path!` declarations for each RPC method
/// - An `API` type alias combining all endpoints
pub fn generate_typeway_from_proto(proto: &ProtoFile) -> String {
    let mut output = String::new();

    // Header comment.
    output.push_str(&format!(
        "//! Generated from proto package `{}`.\n",
        proto.package
    ));
    output.push_str("//!\n");
    output.push_str("//! This file was auto-generated by `typeway-grpc api-from-proto`.\n");
    output.push_str("//! Manual edits may be overwritten.\n\n");

    // Use statements.
    output.push_str("use typeway::prelude::*;\n");
    output.push_str("use serde::{Serialize, Deserialize};\n\n");

    // Generate Rust structs from proto messages.
    for msg in &proto.messages {
        output.push_str(&generate_struct(msg));
        output.push_str("\n\n");
    }

    // Collect endpoint info from service RPCs.
    let mut path_decls = Vec::new();
    let mut endpoint_types = Vec::new();

    for service in &proto.services {
        for method in &service.methods {
            let (http_method, path) = parse_rpc_comment(&method.comment);
            let path_type_name = path_to_type_name(&path);
            let macro_args = path_to_macro_args(&path);

            // typeway_path! declaration.
            path_decls.push(format!(
                "typeway_path!(type {} = {});",
                path_type_name, macro_args
            ));

            // Endpoint type.
            let endpoint = generate_endpoint_type(
                &http_method,
                &path_type_name,
                &method.input_type,
                &method.output_type,
                proto,
            );
            endpoint_types.push(endpoint);
        }
    }

    // Emit path declarations.
    if !path_decls.is_empty() {
        output.push_str("// Path type declarations\n");
        for decl in &path_decls {
            output.push_str(decl);
            output.push('\n');
        }
        output.push('\n');
    }

    // Emit API type.
    if !endpoint_types.is_empty() {
        output.push_str("type API = (\n");
        for ep in &endpoint_types {
            output.push_str(&format!("    {},\n", ep));
        }
        output.push_str(");\n");
    }

    output
}

/// Generate a Rust struct from a parsed proto message.
fn generate_struct(msg: &ParsedMessage) -> String {
    let mut s = String::new();
    // Use a sanitized name (replace dots from nested message flattening).
    let struct_name = msg.name.replace('.', "_");
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    s.push_str(&format!("pub struct {} {{\n", struct_name));
    for field in &msg.fields {
        let rust_type = if field.is_map {
            let key = proto_type_to_rust(
                field.map_key_type.as_deref().unwrap_or("string"),
                false,
                false,
            );
            let value = proto_type_to_rust(
                field.map_value_type.as_deref().unwrap_or("string"),
                false,
                false,
            );
            format!("std::collections::HashMap<{}, {}>", key, value)
        } else {
            proto_type_to_rust(&field.proto_type, field.repeated, field.optional)
        };
        s.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
    }
    s.push('}');
    s
}

/// Map a protobuf type name to a Rust type.
fn proto_type_to_rust(proto_type: &str, repeated: bool, optional: bool) -> String {
    let base = match proto_type {
        "string" => "String",
        "uint32" => "u32",
        "uint64" => "u64",
        "int32" => "i32",
        "int64" => "i64",
        "sint32" => "i32",
        "sint64" => "i64",
        "fixed32" => "u32",
        "fixed64" => "u64",
        "sfixed32" => "i32",
        "sfixed64" => "i64",
        "float" => "f32",
        "double" => "f64",
        "bool" => "bool",
        "bytes" => "Vec<u8>",
        "google.protobuf.Empty" => "()",
        // Message type name: use as-is (replace dots for nested types).
        other => return format_composite(other.replace('.', "_"), repeated, optional),
    };

    if repeated {
        format!("Vec<{}>", base)
    } else if optional {
        format!("Option<{}>", base)
    } else {
        base.to_string()
    }
}

/// Format a composite (message) type with repeated/optional wrappers.
fn format_composite(type_name: String, repeated: bool, optional: bool) -> String {
    if repeated {
        format!("Vec<{}>", type_name)
    } else if optional {
        format!("Option<{}>", type_name)
    } else {
        type_name
    }
}

/// Parse an RPC comment to extract the HTTP method and path.
///
/// Comments look like `"// GET /users/{id}"`.
/// Returns `("GET", "/")` as fallback if the comment is missing or unparseable.
fn parse_rpc_comment(comment: &Option<String>) -> (String, String) {
    if let Some(c) = comment {
        let c = c.trim().trim_start_matches("//").trim();
        let parts: Vec<&str> = c.splitn(2, ' ').collect();
        if parts.len() == 2 {
            let method = parts[0].to_uppercase();
            let path = parts[1].trim().to_string();
            if is_http_method(&method) {
                return (method, path);
            }
        }
    }
    ("GET".to_string(), "/".to_string())
}

/// Check if a string is a valid HTTP method.
fn is_http_method(s: &str) -> bool {
    matches!(
        s,
        "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS"
    )
}

/// Convert a URL path to a type name for use with `typeway_path!`.
///
/// `/users` -> `UsersPath`
/// `/users/{}` -> `UserByIdPath`
/// `/users/{}/posts` -> `UserPostsPath`
fn path_to_type_name(path: &str) -> String {
    let segments: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();

    if segments.is_empty() {
        return "RootPath".to_string();
    }

    let mut parts = Vec::new();
    let mut i = 0;
    while i < segments.len() {
        let seg = segments[i];
        if seg.starts_with('{') {
            // A capture after a resource name — use "ById" suffix.
            parts.push("ById".to_string());
        } else {
            parts.push(capitalize(seg));
        }
        i += 1;
    }

    format!("{}Path", parts.join(""))
}

/// Convert a URL path to `typeway_path!` macro arguments.
///
/// `/users` -> `"users"`
/// `/users/{}` -> `"users" / u32`
/// `/users/{}/posts` -> `"users" / u32 / "posts"`
fn path_to_macro_args(path: &str) -> String {
    let segments: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();

    if segments.is_empty() {
        return "\"\"".to_string();
    }

    let parts: Vec<String> = segments
        .iter()
        .map(|seg| {
            if seg.starts_with('{') {
                // Default capture type — use String since we don't know the
                // actual type from the proto alone.
                "String".to_string()
            } else {
                format!("\"{}\"", seg)
            }
        })
        .collect();

    parts.join(" / ")
}

/// Capitalize the first letter of a string.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => {
            let upper: String = c.to_uppercase().collect();
            upper + &chars.collect::<String>()
        }
        None => String::new(),
    }
}

/// Generate the endpoint type string for an RPC method.
fn generate_endpoint_type(
    http_method: &str,
    path_type: &str,
    input_type: &str,
    output_type: &str,
    proto: &ProtoFile,
) -> String {
    let rust_output = response_type_name(output_type, proto);
    let rust_input = request_type_name(input_type);

    match http_method {
        "GET" | "HEAD" => format!("GetEndpoint<{}, Json<{}>>", path_type, rust_output),
        "POST" => format!(
            "PostEndpoint<{}, Json<{}>, Json<{}>>",
            path_type, rust_input, rust_output
        ),
        "PUT" => format!(
            "PutEndpoint<{}, Json<{}>, Json<{}>>",
            path_type, rust_input, rust_output
        ),
        "PATCH" => format!(
            "PatchEndpoint<{}, Json<{}>, Json<{}>>",
            path_type, rust_input, rust_output
        ),
        "DELETE" => format!("DeleteEndpoint<{}, ()>", path_type),
        _ => format!("GetEndpoint<{}, Json<{}>>", path_type, rust_output),
    }
}

/// Convert a proto response type name to a Rust type reference.
fn response_type_name(proto_type: &str, proto: &ProtoFile) -> String {
    if proto_type == "google.protobuf.Empty" {
        return "()".to_string();
    }
    // Check if this is a known message with a "repeated" wrapper pattern.
    // E.g., ListUserResponse { repeated User users = 1; } -> Vec<User>.
    if let Some(msg) = proto.messages.iter().find(|m| m.name == proto_type) {
        if msg.fields.len() == 1 && msg.fields[0].repeated {
            let inner = msg.fields[0].proto_type.replace('.', "_");
            return format!("Vec<{}>", inner);
        }
    }
    proto_type.replace('.', "_")
}

/// Convert a proto request type name to a Rust type reference.
fn request_type_name(proto_type: &str) -> String {
    if proto_type == "google.protobuf.Empty" {
        return "()".to_string();
    }
    proto_type.replace('.', "_")
}

/// Convenience: parse proto source and generate Rust code in one step.
pub fn proto_to_typeway(source: &str) -> Result<String, String> {
    let proto = crate::proto_parse::parse_proto(source)?;
    Ok(generate_typeway_from_proto(&proto))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proto_parse::{parse_proto, ParsedField};

    const SAMPLE_PROTO: &str = r#"syntax = "proto3";

package users.v1;

service UserService {
  // GET /users
  rpc ListUser(google.protobuf.Empty) returns (ListUserResponse);
  // GET /users/{}
  rpc GetUser(GetUserRequest) returns (User);
  // POST /users
  rpc CreateUser(CreateUserRequest) returns (User);
  // DELETE /users/{}
  rpc DeleteUser(DeleteUserRequest) returns (google.protobuf.Empty);
}

message User {
  uint32 id = 1;
  string name = 2;
  string email = 3;
}

message GetUserRequest {
  string param1 = 1;
}

message CreateUserRequest {
  string name = 1;
  string email = 2;
}

message DeleteUserRequest {
  string param1 = 1;
}

message ListUserResponse {
  repeated User users = 1;
}
"#;

    #[test]
    fn generates_rust_structs() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);
        assert!(output.contains("pub struct User {"));
        assert!(output.contains("pub id: u32,"));
        assert!(output.contains("pub name: String,"));
        assert!(output.contains("pub email: String,"));
    }

    #[test]
    fn generates_typeway_path() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);
        assert!(output.contains("typeway_path!"));
    }

    #[test]
    fn generates_api_type() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);
        assert!(output.contains("type API = ("));
    }

    #[test]
    fn generated_code_mentions_all_endpoints() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);
        assert!(output.contains("GetEndpoint"), "missing GetEndpoint");
        assert!(output.contains("PostEndpoint"), "missing PostEndpoint");
        assert!(output.contains("DeleteEndpoint"), "missing DeleteEndpoint");
    }

    #[test]
    fn roundtrip_proto_to_rust() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);

        // All message structs present.
        assert!(output.contains("pub struct User {"));
        assert!(output.contains("pub struct GetUserRequest {"));
        assert!(output.contains("pub struct CreateUserRequest {"));
        assert!(output.contains("pub struct DeleteUserRequest {"));
        assert!(output.contains("pub struct ListUserResponse {"));

        // API type present.
        assert!(output.contains("type API = ("));

        // Path declarations present.
        assert!(output.contains("typeway_path!(type"));

        // Endpoint types present.
        assert!(output.contains("GetEndpoint"));
        assert!(output.contains("PostEndpoint"));
        assert!(output.contains("DeleteEndpoint"));

        // Serde derives on structs.
        assert!(output.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));

        // Use statements.
        assert!(output.contains("use typeway::prelude::*;"));
        assert!(output.contains("use serde::{Serialize, Deserialize};"));
    }

    #[test]
    fn proto_type_mapping_primitives() {
        assert_eq!(proto_type_to_rust("string", false, false), "String");
        assert_eq!(proto_type_to_rust("uint32", false, false), "u32");
        assert_eq!(proto_type_to_rust("int64", false, false), "i64");
        assert_eq!(proto_type_to_rust("float", false, false), "f32");
        assert_eq!(proto_type_to_rust("double", false, false), "f64");
        assert_eq!(proto_type_to_rust("bool", false, false), "bool");
        assert_eq!(proto_type_to_rust("bytes", false, false), "Vec<u8>");
        assert_eq!(
            proto_type_to_rust("google.protobuf.Empty", false, false),
            "()"
        );
    }

    #[test]
    fn proto_type_mapping_repeated() {
        assert_eq!(proto_type_to_rust("string", true, false), "Vec<String>");
        assert_eq!(proto_type_to_rust("uint32", true, false), "Vec<u32>");
        assert_eq!(proto_type_to_rust("User", true, false), "Vec<User>");
    }

    #[test]
    fn proto_type_mapping_optional() {
        assert_eq!(
            proto_type_to_rust("string", false, true),
            "Option<String>"
        );
        assert_eq!(proto_type_to_rust("uint32", false, true), "Option<u32>");
    }

    #[test]
    fn path_type_name_generation() {
        assert_eq!(path_to_type_name("/users"), "UsersPath");
        assert_eq!(path_to_type_name("/users/{}"), "UsersByIdPath");
        assert_eq!(
            path_to_type_name("/users/{}/posts"),
            "UsersByIdPostsPath"
        );
        assert_eq!(path_to_type_name("/"), "RootPath");
    }

    #[test]
    fn path_macro_args_generation() {
        assert_eq!(path_to_macro_args("/users"), "\"users\"");
        assert_eq!(path_to_macro_args("/users/{}"), "\"users\" / String");
        assert_eq!(
            path_to_macro_args("/users/{}/posts"),
            "\"users\" / String / \"posts\""
        );
    }

    #[test]
    fn parse_rpc_comment_valid() {
        let comment = Some("// GET /users/{id}".to_string());
        let (method, path) = parse_rpc_comment(&comment);
        assert_eq!(method, "GET");
        assert_eq!(path, "/users/{id}");
    }

    #[test]
    fn parse_rpc_comment_none() {
        let (method, path) = parse_rpc_comment(&None);
        assert_eq!(method, "GET");
        assert_eq!(path, "/");
    }

    #[test]
    fn parse_rpc_comment_non_http() {
        let comment = Some("// This is just a regular comment".to_string());
        let (method, path) = parse_rpc_comment(&comment);
        // "This" is not a valid HTTP method, so falls back to default.
        assert_eq!(method, "GET");
        assert_eq!(path, "/");
    }

    #[test]
    fn list_response_unwraps_to_vec() {
        let proto = parse_proto(SAMPLE_PROTO).unwrap();
        let output = generate_typeway_from_proto(&proto);
        // The ListUser endpoint uses ListUserResponse which has `repeated User`,
        // so it should generate Vec<User> in the endpoint type.
        assert!(
            output.contains("Vec<User>"),
            "ListUserResponse should unwrap to Vec<User>"
        );
    }

    #[test]
    fn nested_type_names_sanitized() {
        let msg = ParsedMessage {
            name: "Outer.Inner".to_string(),
            fields: vec![ParsedField {
                name: "value".to_string(),
                proto_type: "string".to_string(),
                tag: 1,
                repeated: false,
                optional: false,
                is_map: false,
                map_key_type: None,
                map_value_type: None,
            }],
        };
        let s = generate_struct(&msg);
        assert!(s.contains("pub struct Outer_Inner {"));
    }

    #[test]
    fn map_field_generates_hashmap() {
        let msg = ParsedMessage {
            name: "Config".to_string(),
            fields: vec![ParsedField {
                name: "metadata".to_string(),
                proto_type: "map<string, string>".to_string(),
                tag: 1,
                repeated: false,
                optional: false,
                is_map: true,
                map_key_type: Some("string".to_string()),
                map_value_type: Some("string".to_string()),
            }],
        };
        let s = generate_struct(&msg);
        assert!(
            s.contains("std::collections::HashMap<String, String>"),
            "Expected HashMap in generated struct: {}",
            s
        );
    }
}
