//! Handler documentation metadata for OpenAPI spec generation.
//!
//! [`HandlerDoc`] captures doc comments from handler functions at compile time
//! (via the `#[documented_handler]` proc-macro) and makes them available for
//! patching into the generated OpenAPI spec at runtime.

/// Documentation metadata extracted from a handler function's doc comments.
///
/// Generated by the `#[documented_handler]` attribute macro. Each annotated
/// handler produces a `const` of this type (named `<SCREAMING_SNAKE>_DOC`)
/// that can be passed to the server's `with_openapi_docs` method.
///
/// # Example
///
/// ```ignore
/// /// List all users.
/// ///
/// /// Returns a paginated list of users with optional filtering.
/// #[documented_handler(tags = "users")]
/// async fn list_users(state: State<Db>) -> Json<Vec<User>> {
///     // ...
/// }
///
/// // Generates: pub const LIST_USERS_DOC: HandlerDoc = HandlerDoc { ... };
///
/// Server::<API>::new(handlers)
///     .with_openapi_docs("My API", "1.0", &[LIST_USERS_DOC])
///     .serve(addr)
///     .await?;
/// ```
#[derive(Debug, Clone, Copy)]
pub struct HandlerDoc {
    /// A short summary (first line of the doc comment).
    pub summary: &'static str,
    /// A longer description (remaining lines of the doc comment).
    pub description: &'static str,
    /// The function name, used as the OpenAPI `operationId`.
    pub operation_id: &'static str,
    /// Tags for grouping operations in the OpenAPI spec.
    pub tags: &'static [&'static str],
}
